// Generated by gencpp from file test/age.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_AGE_H
#define TEST_MESSAGE_AGE_H

#include <ros/service_traits.h>


#include <test/ageRequest.h>
#include <test/ageResponse.h>


namespace test
{

struct age
{

typedef ageRequest Request;
typedef ageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct age
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::age > {
  static const char* value()
  {
    return "f7eb1611265559a9d645d68293c29871";
  }

  static const char* value(const ::test::age&) { return value(); }
};

template<>
struct DataType< ::test::age > {
  static const char* value()
  {
    return "test/age";
  }

  static const char* value(const ::test::age&) { return value(); }
};


// service_traits::MD5Sum< ::test::ageRequest> should match
// service_traits::MD5Sum< ::test::age >
template<>
struct MD5Sum< ::test::ageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::age >::value();
  }
  static const char* value(const ::test::ageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::ageRequest> should match
// service_traits::DataType< ::test::age >
template<>
struct DataType< ::test::ageRequest>
{
  static const char* value()
  {
    return DataType< ::test::age >::value();
  }
  static const char* value(const ::test::ageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::ageResponse> should match
// service_traits::MD5Sum< ::test::age >
template<>
struct MD5Sum< ::test::ageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::age >::value();
  }
  static const char* value(const ::test::ageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::ageResponse> should match
// service_traits::DataType< ::test::age >
template<>
struct DataType< ::test::ageResponse>
{
  static const char* value()
  {
    return DataType< ::test::age >::value();
  }
  static const char* value(const ::test::ageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_AGE_H
