// Generated by gencpp from file test_msgs/timelist.msg
// DO NOT EDIT!


#ifndef TEST_MSGS_MESSAGE_TIMELIST_H
#define TEST_MSGS_MESSAGE_TIMELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_msgs
{
template <class ContainerAllocator>
struct timelist_
{
  typedef timelist_<ContainerAllocator> Type;

  timelist_()
    : data()  {
    }
  timelist_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::test_msgs::timelist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_msgs::timelist_<ContainerAllocator> const> ConstPtr;

}; // struct timelist_

typedef ::test_msgs::timelist_<std::allocator<void> > timelist;

typedef boost::shared_ptr< ::test_msgs::timelist > timelistPtr;
typedef boost::shared_ptr< ::test_msgs::timelist const> timelistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_msgs::timelist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_msgs::timelist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test_msgs::timelist_<ContainerAllocator1> & lhs, const ::test_msgs::timelist_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test_msgs::timelist_<ContainerAllocator1> & lhs, const ::test_msgs::timelist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test_msgs::timelist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_msgs::timelist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_msgs::timelist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_msgs::timelist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_msgs::timelist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_msgs::timelist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_msgs::timelist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const ::test_msgs::timelist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_msgs::timelist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_msgs/timelist";
  }

  static const char* value(const ::test_msgs::timelist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_msgs::timelist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n"
;
  }

  static const char* value(const ::test_msgs::timelist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_msgs::timelist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct timelist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_msgs::timelist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_msgs::timelist_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MSGS_MESSAGE_TIMELIST_H
